name: pdf-project
services:
    mysql:
        container_name: mysql-dream-cup
        image: 'mysql/mysql-server:8.0.32'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - '${DATA_PATH_HOST}/mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    redis:
        container_name: redis-dream-cup.com.ua
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-63799}:6379'
        volumes:
            - '${DATA_PATH_HOST}/redis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
    nginx:
        container_name: nginx-dream-cup
        env_file:
          - .env
        build:
            context: ./docker/nginx
            args:
              APP_CODE_PATH_CONTAINER: ${APP_CODE_PATH_CONTAINER}
        depends_on:
            - php-fpm
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
#            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "5174:5174"
        environment:
          INSTALL_FOLDER: ${APP_CODE_PATH_CONTAINER}
        networks:
            - sail
    php-fpm:
        container_name: php-fpm-dream-cup
        env_file:
          - .env
        user: '${WWW_USER}:${WWW_USER}'
        build:
            context: ./docker/php-fpm
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        networks:
            - sail
        environment:
          INSTALL_FOLDER: ${APP_CODE_PATH_CONTAINER}
        expose:
            - "9000"
    laravel-horizon:
        build:
            context: ./docker/laravel-horizon
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ./docker/laravel-horizon/supervisord.d:/etc/supervisord.d
        depends_on:
            - php-fpm
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
